#' Translations blocks
#'
#' An internal class that encapsulates translations of the same source text.
#'
#' @param hash A non-empty and non-[NA][base::NA] character string. A
#'   reproducible hash generated from `text` and used as a unique identifier
#'   for the underlying [`Block`][Block] object. It is typically generated by
#'   a known [hashing algorithm][get_hash_algorithms()].
#'
#' @param text A non-empty and non-[NA][base::NA] character string. The source
#'   text to be translated.
#'
#' @param text_key A non-empty and non-[NA][base::NA] character string. The
#'   (default) language key of `text`. See [Translations Source Files] for
#'   more information.
#'
#' @param locations A list of [`Location`][Location] objects referencing
#'   `text` in the project. Since `text` can be reused as is multiple times,
#'   it may have multiple locations.
#'
#' @param translations A non-empty named character vector of non-[NA][base::NA]
#'   values. Values are actual translations of `text`. Their names correspond
#'   to the underlying language keys. See [Translations Source Files] for more
#'   information.
#'
#' @returns
#' [block()] returns a named list of class [`Block`][Block] containing the
#' following elements:
#'
#' \describe{
#'   \item{`hash`}{See argument `hash`.}
#'   \item{`text`}{See argument `text`.}
#'   \item{`text_key`}{See argument `text_key`.}
#'   \item{`locations`}{See argument `locations`.}
#'   \item{`translations`}{See argument `translations`.}
#'   \item{`.texts`}{A named character vector constructed from `text`,
#'     `text_key`, and `translations`. It combines all three elements into
#'     a single vector and is equivalent to `c(text_key = text, translations)`.}
#' }
#'
#' [is_block()] returns a logical.
#'
#' [format.Block()] returns a character string.
#'
#' [print.Block()] returns argument `x` invisibly.
#'
#' @note
#' [block()] does **not** generate hashes. This must be done *before* creating
#' instances of the class. This is because [`Block`][Block] is just a semantic
#' container.
#'
#' @aliases Block
#' @rdname class-block
#' @keywords internal
block <- function(
    hash         = "",
    text         = "",
    text_key     = "",
    locations    = list(),
    translations = character())
{
    assert_chr1(hash)
    assert_chr1(text)
    assert_chr1(text_key)
    assert_list(locations)

    if (!all(vapply_1l(locations, is_location))) {
        stops("'locations' must only contain 'Location' objects.")
    }

    translations <- unlist(translations)
    assert_chr(translations)
    assert_named(translations)

    .texts        <- c(text, translations)
    names(.texts) <- c(text_key, names(translations))


    return(
        structure(
            list(
                hash         = hash,
                text         = text,
                text_key     = text_key,
                locations    = locations,
                translations = translations,
                .texts       = .texts),
            class = c("Block", "list")))
}

#' @rdname class-block
#' @keywords internal
is_block <- function(x) {
    return(inherits(x, "Block"))
}

#' @rdname class-block
#' @export
format.Block <- function(x, ...) {
    # Restructuring x allows us to
    # call paste0() only once below.
    x <- list(
        "Hash     : "  = x$hash,
        "Text     : "  = x$text,
        "Text key : "  = x$text_key,
        "Lang keys: "  = to_string(names(x$.texts), TRUE, ", "),
        "Locations:\n" = paste0(
            " - ",
            vapply_1c(x$locations, format),
            collapse = "\n"))

    return(paste0(names(x), x))

}

#' @rdname class-block
#' @export
print.Block <- function(x, ...) {
    cat("<Block> ", format(x, ...), sep = "\n")
    return(invisible(x))
}
