#' Translations blocks
#'
#' The [Block] class is an internal class that encapsulates a collection
#' of translations of the same source text identified by a reproducible
#' hash. Users typically never directly interact with [Block] objects.
#'
#' @param hash A non-empty and non-[NA][base::NA] character string. This is
#'   typically a reproducible hash generated by a known
#'   [hashing algorithm][get_hash_algorithms()] from the source text (as it
#'   appears in source scripts).
#'
#' @param translations A non-empty named character vector of non-[NA][base::NA]
#'   values. The names state to which languages they correspond. Users have
#'   full control over the names and are free to use whatever they want. Since
#'   they do not need to represent the full name of a language, names are
#'   referred to as *language keys*. See Examples below.
#'
#' @returns
#' [new_block()] returns a list of length 2 of class [Block] and containing
#' these two elements: the values of `hash` and `translations`.
#'
#' [is_block()] returns a logical.
#'
#' @note
#' [new_block()] does not generate hashes. This must be done before creating
#' instances of the class.
#'
#' @examples
#' source_text <- "Hello, world!"
#'
#' ## This is just a dummy example and not truly a hash per se.
#' hash <- source_text |>
#'     paste0(collapse = " ") |>
#'     charToRaw() |>
#'     paste0(collapse = "")
#'
#' translations <- c(
#'     fr        = "Bonjour le monde!",
#'     es        = "¡Hola Mundo!",
#'     `jp-utf8` = "こんにちは世界！")
#'
#' my_block <- new_block(hash, translations)
#'
#' @rdname class-block
#' @keywords internal
new_block <- function(hash = "", translations = character()) {
    assert_chr1(hash)
    assert_chr(translations)
    assert_names(translations)

    return(
        structure(
            list(hash = hash, translations = translations),
            class = c("Block", "list")))
}

#' @rdname class-block
#' @keywords internal
is_block <- function(x) {
    return(inherits(x, "Block"))
}
