#' Translations Source Files
#'
#' A *translations source file* (TSF) is a plain text Markdown file (most
#' likely) generated by [write_translations()]. It contains source translations
#' and relevant metadata. It can be viewed as a portable and human-readable
#' serialization of a [`Translator`][Translator] object. It is meant to be
#' easily sharable with non-technical collaborators such as translators and
#' reviewers.
#'
#' @details
#  TODO: complete this section once set_translator() is implemented.
#' A project may use more than one TSF if required. The actual mechanism to
#' do so is yet to be determined (coming soon).
#'
#' A TSF may be imported back into a \R session with function
#' [read_translations()]. The latter converts it to a [`Translator`][Translator]
#' object.
#'
#' @section Sharing Translations Source Files:
#' The intent behind TSFs is to be shared with non-technical and/or external
#' collaborators such as professional translators. They may iterate on them
#' by modifying and expanding the contents of **existing** source blocks.
#' Their contribution will be used at runtime when the files are converted
#' back into [`Translator`][Translator] objects. See below for details.
#'
#' @section General Sructure:
#' A TSF is divided into two parts: the *header* and the *translations*. It
#' follows the usual syntax of [CommonMark](https://commonmark.org/) with
#' one exception: it requires a [YAML](https://yaml.org/) header.
#'
#' Translations are further split into so-called *blocks*. Each block contains
#' source information and translations.
#'
#' ## Header
#'
#' The header contains metadata required for parsing purposes. You may add
#' further fields to the header in no preferred order. It must be enclosed by
#' a pair of separators (`---`). In-line headers are allowed but discouraged.
#'
#' The contents is always formatted according to what [YAML](https://yaml.org/)
#' prescribes. What it *must* include depends on the `template_version`. This
#' field is mandatory no matter the version and is used for parsing purposes.
#' See sections below.
#'
#' ## Blocks
#'
#' A TSF contains one or more blocks. Each source text that must be translated
#' has a corresponding block. Blocks are mutually independent and are parsed
#' individually. They are not required to contain translations under the same
#' language(s). How they are structured depends on the underlying values of
#' header's field `template_version`. See sections below.
#'
#' A block always has at least four components.
#'
#' 1. The **source text** to be translated.
#'
#' 2. A **reproducible hash** generated from the source text. It is used as a
#'    unique identifier for the underlying block.
#'
#' 3. The **location** of the source text in the project. Since the same source
#'    text can be reused multiple times, it **may have multiple locations**.
#'
#' 4. One or more **translations** of the source text. Each translation has
#'    a corresponding *language key*. See section *Language keys* below.
#'
#' Each block is parsed as a [`Block`][Block] object internally.
#'
#' @section Language Keys:
#' Package [`transltr`][transltr] uses so-called *language keys* to uniquely
#' identify a native language in a (possibly) more concise way. This is
#' convenient for portability and universality. For example, `日本語` (Japanese
#' or Nihongo) could be identified by the ASCII string `jp` (or `jp-utf8`,
#' `jp-eucjp`, etc.) in TSFs.
#'
#' Language keys can be (almost) any character string. Users have full control
#' over them and are free to use whatever they want.
#'
#' Language keys appear in blocks but the header (usually) contains a global
#' mandatory field `language_keys` which maps keys to full native language
#' names.
#'
#' ```yaml
#' language_keys:
#'   language-key-1: full-native-language-name-1
#'   language-key-2: full-native-language-name-2
#'   ...
#' ```
#'
#' @section Template version 1:
#'
#' This is the current default version.
#'
#' ## Header
#'
#' There are `6` mandatory header fields. They must be left as is. Users may
#' only modify and/or add further entries to `language_keys`.
#'
#' | **Field**          | **YAML type** | **R type**                | **Example**                                           |
#' | ------------------ | ------------- | ------------------------- | ----------------------------------------------------- |
#' | `template_version` | Integer       | `integer(1)`              | `1`                                                   |
#' | `generated_by`     | String        | `character(1)`            | `R package transltr 0.0.1`                            |
#' | `generated_on`     | String        | `character(1)`            | `August 22, 2024 @ 08:00 UTC`                         |
#' | `hash_algorithm`   | String        | `character(1)`            | `blake2b`                                             |
#' | `hash_length`      | Integer       | `integer(1)`              | `32`                                                  |
#' | `language_keys`    | Map           | `character()`<br/>(Named) | `fr: Français`<br/>`language-key: full-language-name` |
#'
#' ## Blocks
#'
#' Blocks are structured according to this template. Spaces before and after
#' titles (`#` and `##`) are ignored.
#'
#' ```md
#' # {{ source-text-reproducible-hash }}
#'
#' `{{ source-file-path }}`:
#'
#'   {{ source-range-1 }}
#'   ...
#'
#' ## {{ source-language-key }}
#'
#' Extracted source text (as is).
#'
#' ## language-key-A
#'
#' Source text translated in language A.
#'
#' ## language-key-B
#'
#' Source text translated in language B.
#'
#' ...
#' ```
#'
#' Blocks may be referenced by multiple source files and/or ranges.
#'
#' ## Rules
#'
#' There are three **important rules to follow**.
#'
#' * Never manually modify sections whose names are enclosed by
#'   `` `{{ `` and `` }}` ``.
#'
#' * Never manually add further (new) blocks. They are generated automatically
#'   from source scripts.
#'
#' * Ensure all language keys have a corresponding entry in  header's field
#'   `language_keys`.
#'
#' @seealso [read_translations()],
#'   [write_translations()],
#'   [from_tsf()],
#    TODO: transform this comment into #' once implemented.
#    [to_tsf()],
#'   [new_block()]
#'
#' @rdname tsf
#' @name Translations Source Files
NULL
